language: csharp
solution: testrunner.sln
script:
  - xbuild /p:Configuration=Debug testrunner.sln
  - mono --debug ./TestRunner/bin/Debug/net461/TestRunner.exe ./TestRunner.Tests/bin/Debug/net461/TestRunner.Tests.dll
