language: csharp
mono: none
dotnet: 2.1.4
script:
  - dotnet build -f netcoreapp2.0
  - dotnet publish -f netcoreapp2.0 testrunner/testrunner.csproj
  - dotnet publish -f netcoreapp2.0 testrunner.Tests.MSTest/testrunner.Tests.MSTest.csproj
  - dotnet testrunner/bin/Debug/netcoreapp2.0/publish/testrunner.dll --inproc testrunner.Tests.MSTest/bin/Debug/netcoreapp2.0/publish/testrunner.Tests.MSTest.dll
