language: csharp
solution: testrunner.sln
install:
  - nuget install TestRunner -OutputDirectory packages
script:
  - xbuild /p:Configuration=Debug testrunner.sln
  - mono --debug --runtime=v4.0 ./packages/TestRunner.*/tools/TestRunner.exe ./TestRunner.Tests/bin/Debug/TestRunner.Tests.dll

